### ISSUE TITLE
Control.OSMGeocoder.js

### ISSUE THREAD

**Issue by azstumbler** [k4r573n/leaflet-control-osm-geocoder#10]
Using QGIS2Web to generate leaflet maps from QGIS. Within the last 2 weeks the maps stopped displaying, they will load but nothing will show. I have leaflet installed locally and those controls that QGIS2Web reference off site all seems to be working except http://k4r573n.github.io/leaflet-control-osm-geocoder/Control.OSMGeocoder.js which returns a page not found. Has this gone offline?

**Comment by k4r573n** [comment]
Yes I've cleaned up the project a few days ago. To prevent the demo to outdate I replaced the library you search by https://rawgit.com/k4r573n/leaflet-control-osm-geocoder/master/Control.OSMGeocoder.js
which referes always to the newest version.
